# .goreleaser.yml
version: 2

project_name: hypertunnel

# Build configuration
builds:
  - id: ht
    main: ./main.go
    binary: ht
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/abrekhov/hypertunnel/cmd.Version={{.Version}}
      - -X github.com/abrekhov/hypertunnel/cmd.Commit={{.Commit}}
      - -X github.com/abrekhov/hypertunnel/cmd.Date={{.Date}}

# Disable archiving
archives:
  # Raw binaries (stable names) for the GitHub Pages installer.
  - id: raw-binaries
    formats: binary
    name_template: "ht_{{ .Os }}_{{ .Arch }}"
    ids:
      - ht

  # Compressed archives for users (stable names).
  - id: archives
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "hypertunnel_{{ .Os }}_{{ .Arch }}"
    ids:
      - ht

# Generate checksums for the binaries
checksum:
  name_template: 'checksums.txt'

# Debian packages
nfpms:
  - id: hypertunnel
    package_name: hypertunnel
    maintainer: Anton Brekhov <anton@abrekhov.ru>
    description: P2P file transfer tool using WebRTC
    homepage: https://github.com/abrekhov/hypertunnel
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    scripts:
      postinstall: scripts/postinstall.sh
    file_name_template: "hypertunnel_{{ .Os }}_{{ .Arch }}"
    ids:
      - ht

# Homebrew formula
brews:
  - name: hypertunnel
    ids:
      - raw-binaries
    repository:
      owner: abrekhov
      name: homebrew-hypertunnel
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/abrekhov/hypertunnel
    description: P2P file transfer tool using WebRTC
    license: Apache-2.0
    install: |
      # Assets are published as raw binaries (e.g. ht_darwin_arm64).
      # Install whichever one Homebrew downloaded, renaming it to `ht`.
      bin.install Dir["ht_*"][0] => "ht"
    test: |
      system "#{bin}/ht", "--help"

# Release configuration
release:
  github:
    owner: abrekhov
    name: hypertunnel
