# .goreleaser.yml
version: 2

project_name: hypertunnel

# Build configuration
builds:
  - id: ht
    main: ./main.go
    binary: ht
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

# Disable archiving
archives:
  - formats: binary
    name_template: "ht_{{ .Os }}_{{ .Arch }}"
    ids:
      - ht

# Generate checksums for the binaries
checksum:
  name_template: 'checksums.txt'

# Debian packages
nfpms:
  - id: hypertunnel
    package_name: hypertunnel
    maintainer: Anton Brekhov <anton@abrekhov.ru>
    description: P2P file transfer tool using WebRTC
    homepage: https://github.com/abrekhov/hypertunnel
    license: Apache-2.0
    formats:
      - deb
    bindir: /usr/local/bin
    ids:
      - ht

# Homebrew formula
brews:
  - name: hypertunnel
    repository:
      owner: abrekhov
      name: homebrew-hypertunnel
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/abrekhov/hypertunnel
    description: P2P file transfer tool using WebRTC
    license: Apache-2.0
    install: |
      bin.install "ht"
    test: |
      system "#{bin}/ht", "--help"

# Release configuration
release:
  github:
    owner: abrekhov
    name: hypertunnel
