# .github/workflows/release.yaml

on:
  push

jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: go version
    - run: go mod download
    - run: ls
    - run: go build -o ./ht
    - run: ls
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: ht