# .github/workflows/release.yaml

on:
  push

jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: go version
    - run: go mod download
    - run: ls
    - run: mkdir build
    - run: go build -o build/ht
    - run: ls build
    - name: Download a single artifact
      uses: actions/upload-artifact@v3
      with:
        name: ht
        path: build/ht
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/ht